@URL=http://localhost:8081/atuador


### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcyODU2NjksImV4cCI6MTcxNzMyMTY2OSwiaXNzIjoiVVRGUFIifQ.27TPTSlmg7hSQe7_YwOusXKoweCPnxqS6Tm0oFiVFwM

{
    "nome": "HUDUHAUS",
    "idDispositivo": 1
}

### GET ALL
GET {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcyODU2NjksImV4cCI6MTcxNzMyMTY2OSwiaXNzIjoiVVRGUFIifQ.27TPTSlmg7hSQe7_YwOusXKoweCPnxqS6Tm0oFiVFwM



### GET BY ID
GET {{URL}}/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcyMDIxNjQsImV4cCI6MTcxNzIzODE2NCwiaXNzIjoiVVRGUFIifQ.2hgLY_LJaSPwL207u7uFfKbThiSNNUpNqc6x4CNaDH0

### DELETE
DELETE {{URL}}/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcyMDIxNjQsImV4cCI6MTcxNzIzODE2NCwiaXNzIjoiVVRGUFIifQ.2hgLY_LJaSPwL207u7uFfKbThiSNNUpNqc6x4CNaDH0