@URL=http://localhost:8081/atuador


### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxOTAwNjIsImV4cCI6MTcxNzIyNjA2MiwiaXNzIjoiVVRGUFIifQ.Pz0yLe6qgnMnhAdA0x8vG6r9f4MWyCyG6MSyb-OD9rg

{
    "nome": "HUDUHAUS",
    "idDispositivo": 1
}

### GET ALL
GET {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImFhc3NkZGZmYUBtYWlsLmNvbSIsImlhdCI6MTcxNjk0NDc0NSwiZXhwIjoxNzE2OTgwNzQ1LCJpc3MiOiJVVEZQUiJ9.ofTI5zHz1o6HE3zpleppZAw6YEsPT4Or-xkCWZOfkS8



### GET BY ID
GET {{URL}}/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcyMDIxNjQsImV4cCI6MTcxNzIzODE2NCwiaXNzIjoiVVRGUFIifQ.2hgLY_LJaSPwL207u7uFfKbThiSNNUpNqc6x4CNaDH0

### DELETE
DELETE {{URL}}/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcyMDIxNjQsImV4cCI6MTcxNzIzODE2NCwiaXNzIjoiVVRGUFIifQ.2hgLY_LJaSPwL207u7uFfKbThiSNNUpNqc6x4CNaDH0