@URL=http://localhost:8081/dispositivo

### CREATE
POST {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmFAZ21haWwuY29tIiwiaWF0IjoxNzE3MjczMTc2LCJleHAiOjE3MTczMDkxNzYsImlzcyI6IlVURlBSIn0.unHNljFN6e5Q6A2W6NtlCyLY3wemG34l3IJAzYo25eo
Content-Type: application/json


{
    "nome":"dispositivo 3",
    "descricao": "dusahwuha",
    "localizacao":"fefesfe",
    "endereco":"udhaueaf",
    "idGateway": 1
}

### GET BY ID
GET {{URL}}/3
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxODcwMjIsImV4cCI6MTcxNzIyMzAyMiwiaXNzIjoiVVRGUFIifQ.oEHn7buRjSSOUlv4jjYymjcbI3Db3zWRNP4DLWgd7U8