@URL=http://localhost:8081/gateway


### CREATE
POST {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiI0IiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxMzAzNzQsImV4cCI6MTcxNzE2NjM3NCwiaXNzIjoiVVRGUFIifQ.4xSWQraTHoMy7SfV3lqKuZJ-uX__IZZl7tQda3Ubjao
Content-Type: application/json

{
    "nome": "gateway2",
    "descricao": "bdauwhdwhuwd",
    "endereco": "jjjdwhjhj",
    "idPessoa": 1
}

### GET ALL
GET {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiI0IiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxMzAzNzQsImV4cCI6MTcxNzE2NjM3NCwiaXNzIjoiVVRGUFIifQ.4xSWQraTHoMy7SfV3lqKuZJ-uX__IZZl7tQda3Ubjao

