@URL=http://localhost:8081/leitura


### CREATE
POST {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmFAZ21haWwuY29tIiwiaWF0IjoxNzE3MjczMjgzLCJleHAiOjE3MTczMDkyODMsImlzcyI6IlVURlBSIn0.7I3IpVIIRzqHYZIWE8dFMprwQO7zo1mdxC69ygT8rQw
Content-Type: application/json

{
    "valor": "fehahaj",
    "idSensor": 1
}

### GET BY ID
GET {{URL}}/3
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcyODU2NjksImV4cCI6MTcxNzMyMTY2OSwiaXNzIjoiVVRGUFIifQ.27TPTSlmg7hSQe7_YwOusXKoweCPnxqS6Tm0oFiVFwM
