@URL=http://localhost:8081/leitura


### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VyZW1haWwiOiJhQGdtYWlsLmNvbSIsImlhdCI6MTcxNjkzMjEyNCwiZXhwIjoxNzE2OTY4MTI0LCJpc3MiOiJVVEZQUiJ9.63HHQl7SzewnyE46YMF3BXvcWa300Vq_WIOVOCg_CTc

{
    "valor": "0",
    "idSensor": 1
}

### GET BY ID
GET {{URL}}/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VyZW1haWwiOiJhQGdtYWlsLmNvbSIsImlhdCI6MTcxNjkzMjEyNCwiZXhwIjoxNzE2OTY4MTI0LCJpc3MiOiJVVEZQUiJ9.63HHQl7SzewnyE46YMF3BXvcWa300Vq_WIOVOCg_CTc
