@URL=http://localhost:8081/pessoa


### CREATE
POST {{URL}}
Content-Type: application/json

{
    "nome": "ana",
    "email": "a@gmail.com",
    "senha": "123"
}

### GET ALL
GET {{URL}}


### GET BY ID
GET {{URL}}/1

### DELETE
DELETE {{URL}}/1

### ATUALIZAR
PUT {{URL}}/1
Content-Type: application/json

{
    "nome": "HUUHHAUS",
    "email": "dhieuhue"
}