@URL=http://localhost:8083/pessoa


### CREATE
POST {{URL}}
Content-Type: application/json

{
    "nome": "ana",
    "email": "ana2@gmail.com",
    "senha": "123"
}

### GET ALL
GET {{URL}}


### GET BY ID
GET {{URL}}/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VybmFtZSI6ImFuYUBnbWFpbC5jb20iLCJpYXQiOjE3MTY5NDgxMzIsImV4cCI6MTcxNjk4NDEzMiwiaXNzIjoiVVRGUFIifQ.Hv7QT_JtEnq7bDjttV8GPOa9dXk4vmyKYhzSM65cp_A

### DELETE
DELETE {{URL}}/1

### ATUALIZAR
PUT {{URL}}/1
Content-Type: application/json

{
    "nome": "HUUHHAUS",
    "email": "dhieuhue"
}