@URL=http://localhost:8081/sensor


### CREATE
POST {{URL}}
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxOTAwNjIsImV4cCI6MTcxNzIyNjA2MiwiaXNzIjoiVVRGUFIifQ.Pz0yLe6qgnMnhAdA0x8vG6r9f4MWyCyG6MSyb-OD9rg

{
    "nome": "HUDUHAUS",
    "tipo": "eaff",
    "idDispositivo": 1
}



### GET ALL
GET {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxOTg0ODYsImV4cCI6MTcxNzIzNDQ4NiwiaXNzIjoiVVRGUFIifQ.Yt7Nl_2jCRN8_nJJTBYmqvdbQnJ8EppP29mzC8H5s8A


### GET BY ID
GET {{URL}}
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxOTg0ODYsImV4cCI6MTcxNzIzNDQ4NiwiaXNzIjoiVVRGUFIifQ.Yt7Nl_2jCRN8_nJJTBYmqvdbQnJ8EppP29mzC8H5s8A
### DELETE
DELETE {{URL}}/2
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBUEkgYXV0aGVudGljYXRpb24iLCJ1c2VySWQiOiIxIiwidXNlcm5hbWUiOiJhbmEiLCJpYXQiOjE3MTcxOTg0ODYsImV4cCI6MTcxNzIzNDQ4NiwiaXNzIjoiVVRGUFIifQ.Yt7Nl_2jCRN8_nJJTBYmqvdbQnJ8EppP29mzC8H5s8A